-- MySQL Script generated by MySQL Workbench
-- Thu Apr 20 07:22:22 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema webservice_requisition
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema webservice_requisition
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `webservice_requisition` DEFAULT CHARACTER SET utf8 ;
USE `webservice_requisition` ;

-- -----------------------------------------------------
-- Table `webservice_requisition`.`Company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webservice_requisition`.`Company` (
  `Company_ID` INT(5) NOT NULL AUTO_INCREMENT,
  `Company_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Company_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webservice_requisition`.`Requisition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webservice_requisition`.`Requisition` (
  `Requisition_ID` INT(5) NOT NULL AUTO_INCREMENT,
  `Company_ID` INT(5) NOT NULL,
  `Requisition_DATE` DATETIME NOT NULL,
  `Requisition_Desc` VARCHAR(200) NULL,
  `Requisition_Count` INT(5) NOT NULL,
  `Requisition_Status` VARCHAR(1) NOT NULL COMMENT 'A = Active\nC = Cancelled',
  PRIMARY KEY (`Requisition_ID`, `Company_ID`),
  INDEX `fk_Requisition_Company1_idx` (`Company_ID` ASC),
  CONSTRAINT `fk_Requisition_Company1`
    FOREIGN KEY (`Company_ID`)
    REFERENCES `webservice_requisition`.`Company` (`Company_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webservice_requisition`.`Branch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webservice_requisition`.`Branch` (
  `Branch_ID` INT(5) NOT NULL AUTO_INCREMENT,
  `Company_ID` INT(5) NOT NULL,
  `Branch_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Branch_ID`, `Company_ID`),
  INDEX `fk_Branch_Company_idx` (`Company_ID` ASC),
  CONSTRAINT `fk_Branch_Company`
    FOREIGN KEY (`Company_ID`)
    REFERENCES `webservice_requisition`.`Company` (`Company_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webservice_requisition`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webservice_requisition`.`Product` (
  `Product_ID` INT(5) NOT NULL AUTO_INCREMENT,
  `Company_ID` INT(5) NOT NULL,
  `Branch_ID` INT(5) NOT NULL,
  `Product_Name` VARCHAR(45) NOT NULL COMMENT 'ชื่อสินค้า',
  `Product_Price` DECIMAL(5,0) NOT NULL COMMENT 'ราคาต่อหน่วย',
  `Product_InHand` INT(5) NOT NULL COMMENT 'สินค้าที่เหลืออยู่',
  PRIMARY KEY (`Product_ID`, `Company_ID`, `Branch_ID`),
  INDEX `fk_Product_Branch1_idx` (`Branch_ID` ASC, `Company_ID` ASC),
  CONSTRAINT `fk_Product_Branch1`
    FOREIGN KEY (`Branch_ID` , `Company_ID`)
    REFERENCES `webservice_requisition`.`Branch` (`Branch_ID` , `Company_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webservice_requisition`.`LineItem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webservice_requisition`.`LineItem` (
  `LineItem_ID` INT(5) NOT NULL AUTO_INCREMENT,
  `Product_ID` INT(5) NOT NULL,
  `Requisition_ID` INT(5) NOT NULL,
  `LineItem_Qty` INT(5) NULL COMMENT 'จำนวนสินค้าที่เบิก',
  `LineItem_Total` DECIMAL(7,0) NULL COMMENT 'ราคารวมของสินค้าที่เบิก',
  PRIMARY KEY (`LineItem_ID`, `Product_ID`, `Requisition_ID`),
  INDEX `fk_LineItem_Product1_idx` (`Product_ID` ASC),
  INDEX `fk_LineItem_Requisition1_idx` (`Requisition_ID` ASC),
  CONSTRAINT `fk_LineItem_Product1`
    FOREIGN KEY (`Product_ID`)
    REFERENCES `webservice_requisition`.`Product` (`Product_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LineItem_Requisition1`
    FOREIGN KEY (`Requisition_ID`)
    REFERENCES `webservice_requisition`.`Requisition` (`Requisition_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `webservice_requisition`.`Company`
-- -----------------------------------------------------
START TRANSACTION;
USE `webservice_requisition`;
INSERT INTO `webservice_requisition`.`Company` (`Company_ID`, `Company_Name`) VALUES (1, 'Arthur\'s Company');
INSERT INTO `webservice_requisition`.`Company` (`Company_ID`, `Company_Name`) VALUES (2, 'Pranee\'s Company');
INSERT INTO `webservice_requisition`.`Company` (`Company_ID`, `Company_Name`) VALUES (3, 'Tang\'s Company');

COMMIT;


-- -----------------------------------------------------
-- Data for table `webservice_requisition`.`Branch`
-- -----------------------------------------------------
START TRANSACTION;
USE `webservice_requisition`;
INSERT INTO `webservice_requisition`.`Branch` (`Branch_ID`, `Company_ID`, `Branch_Name`) VALUES (1, 1, 'Arthur\'s Company at Rangsit');
INSERT INTO `webservice_requisition`.`Branch` (`Branch_ID`, `Company_ID`, `Branch_Name`) VALUES (2, 1, 'Arthur\'s Company at Ladprao');

COMMIT;


-- -----------------------------------------------------
-- Data for table `webservice_requisition`.`Product`
-- -----------------------------------------------------
START TRANSACTION;
USE `webservice_requisition`;
INSERT INTO `webservice_requisition`.`Product` (`Product_ID`, `Company_ID`, `Branch_ID`, `Product_Name`, `Product_Price`, `Product_InHand`) VALUES (1, 1, 1, 'สบู่', 30, 99);
INSERT INTO `webservice_requisition`.`Product` (`Product_ID`, `Company_ID`, `Branch_ID`, `Product_Name`, `Product_Price`, `Product_InHand`) VALUES (2, 1, 2, 'ยาสีฟัน', 20, 99);

COMMIT;

